### PR TITLE
Better/more complete german translation

### PR DESCRIPTION
**Pull request by BlackDuck888**

### CODE REVIEW

**Comment by rrjanbiah** [comment]
@BlackDuck888 Thanks a lot for your contribution. We'll check and merge

**Comment by rrjanbiah** [comment]
@lmarikannan Please don't miss wonderful contributions from @BlackDuck888

If translations strings are programmed to be automatically pulled from transifex, probably, add his strings directly in transifex itself (instead of merging it). That may help other translators too.

**Comment by BlackDuck888** [comment]
@rrjanbiah 
if have done the translations in transifex, after that i download them and put them in this pull request.
if the translation should download automatically, maybe there was an problem that cause the old translation file.

Should i delete this pull request?

**Comment by rrjanbiah** [comment]
@BlackDuck888 Please don't delete your pull request.

**Comment by BlackDuck888** [comment]
@rrjanbiah 
i will delete this pull request, and create a new one with 100% german translation in dev branch. i did some faults in git checkin's (my first steps with github)

**Comment by rrjanbiah** [comment]
@BlackDuck888 OK sure. No problem. Thanks

**Comment by BlackDuck888** [comment]
Closing this pullrequest, a new more recent translation is created in an other pull request

**Pull request closed without merging**
