### PR TITLE
fix(server): remove GLOB_BRACES

### PR DESCRIPTION
**Pull request by BlackDark**
* See #2282 . 
This is the commit: https://github.com/LittleFox94/board/commit/3d8ad8bc910c7ef18704821f90ee51a29682272e

~~Related to #4013 but not needed there.~~

#4013 only works with this changes correctly.

And from: https://www.php.net/manual/de/function.glob.php it is not needed because no braces are used at all.

### CODE REVIEW

**Comment by LittleFox94** [comment]
Originally changed to allow the use of the PHP version alpine packages

GLOB_BRACES is a glibc extension. Alpine uses musl instead, which doesn't have (or didn't have, not checked again) this feature

**Comment by BlackDark** [comment]
image

**Comment by BlackDark** [comment]
@rrjanbiah could you take a look if this changes are possible and do not break anything?

**Comment by rrjanbiah** [comment]
@BlackDark and @LittleFox94

Yes. Looks like `GLOB_BRACES` is unnecessary. Merging now. Thank you.

**Pull request merged**
