### PR TITLE
Add docker related scripts

### PR DESCRIPTION
**Pull request by BlackDark**
Add some scripts for faster building of docker image

### CODE REVIEW

**Comment by sridhar391** [comment]
@BlackDark 

```
sudo docker run --name restyaboard --publish 8081:8081 --detach restyaplatform/restyaboard:dev
sudo docker start restyaboard
sudo docker ps
```

We have used above command to start Restyaboard in docker but its not working. Can you please provide steps or command to execute Restyaboard using docker?

**Comment by sridhar391** [comment]
Thank You. We will check and update you.

**Comment by BlackDark** [comment]
Hey, could you paste the used `docker-compose.yml` file?

**Comment by sridhar391** [comment]
We have ran `grunt build:docker` to create `restyaboard-docker.zip` file.

Then we have ran `sudo docker-compose up -d` docker image generated successfully. But at last we are getting below error,

```
Recreating 285957cd66ce_285957cd66ce_285957cd66ce_board_postgres_1

ERROR: for postgres  No such image: sha256:6583932564f8ffb63b52643f1355a1a3e738f0cc4d1aeba6500239e63267feb1
ERROR: Encountered errors while bringing up the project.
```

> (Did you update the travis configuration with the login data for docker hub? As mentioned here: #1841 ?)

Yes. We have updated in travis configuration.

**Comment by BlackDark** [comment]
Could you try to clean up docker.

1. Clear the started compose via `docker-compose down`
2. Clean up all images (see `docker images`). Nice commands here: https://gist.github.com/bastman/5b57ddb3c11942094f8d0a97d461b430
3. Then try again with `docker-compose up -d`

**Comment by sridhar391** [comment]
@BlackDark Thank you for the command. After cleanup the old images, restyaboard working fine using docker.

**Pull request merged**
