### PR TITLE
Fix activity bug when loading activities

### PR DESCRIPTION
**Pull request by BlackDark**
## Description

In our usage i discovered a strange problem when loading the activities. Suddenly it doesn't work anymore and i checked the network activities for a clue. The request for the activties did come back but contained some warnings from php that the object is no string. This was a problem with the `$key`s 'activities' and 'checklist_items'. I added the check for them and refactored the code a bit.

I don't know if you like to separate the code but i think it is better maintainable if you have classes with their responsibilities :).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by lmarikannan** [comment]
@BlackDark We're checked your pull request and changes. We got below error 

```

<br />
<b>Catchable fatal error</b>:  Argument 1 passed to getRevisiondifference() must be an instance of string, string given, called in /usr/share/nginx/html/board/server/php/libs/ActivityHandler.php on line 48 and defined in <b>/usr/share/nginx/html/board/server/php/libs/core.php</b> on line <b>387</b><br />

```
because of this change `function getRevisiondifference(string $from_text, string $to_text)` on core.php file.

**Comment by BlackDark** [comment]
@lmarikannan are you using a php version < 7?
https://stackoverflow.com/questions/4103480/how-to-resolve-argument-1-passed-to-my-function-must-be-an-instance-of-string/4103533#4103533

**Comment by lmarikannan** [comment]
@BlackDark We're checking from php version 5.6, In our restyaboard installation script, we're force to install php 7. But some or our customers are used php 5.6. So while checking on php  5.6, we got this error.

> https://stackoverflow.com/questions/4103480/how-to-resolve-argument-1-passed-to-my-function-must-be-an-instance-of-string/4103533#4103533

In this link, they're checking the value whether it's the string or not. So we need to check the values are string or not and then pass the params to `getRevisiondifference(string $from_text, string $to_text)` function. or we can remove String from function params.

**Comment by rrjanbiah** [comment]
@lmarikannan Can we please make necessary changes for PHP 5 compatibility and merge?

**Pull request merged**
